name: Update deny list on clients

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout First Repository
        uses: actions/checkout@v2

      - name: Determine File Changes
        id: file_changes
        run: |
          echo "::set-output name=changes::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

      - name: Skip If No File Changes
        run: |
          if [ -z "${{ steps.file_changes.outputs.changes }}" ]; then
            echo "No changes detected in the apple-app-site-association file. Skipping update."
            exit 0
          fi

      - name: Read apple-app-site-association
        id: read_aasa
        run: |
          content=$(cat apple-app-site-association)
          echo "::set-output name=aasa_content::$content"

      - name: Extract excludedProducts
        id: extract_excluded_products
        run: |
          aasa_content=$(cat apple-app-site-association)
          echo "aasa_content: $aasa_content"
          excluded_products=$(echo "$aasa_content" | jq -r '.applinks.substitutionVariables.excludedProducts | join(", ")' | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')
          echo "excluded_products: $excluded_products"
          echo "::set-output name=excluded_products::$excluded_products"

      - name: Checkout Second Repository
        uses: actions/checkout@v2
        with:
          repository: esraaapady/New-Repository  # Replace with the name of the second repository
          token: ${{ secrets.PAT_TOKEN }}

      - name: Print Current Working Directory
        run: |
          pwd
        working-directory: ${{ github.workspace }}

      - name: Update denylistedFirstPathComponents
        run: |
          excluded_products="${{ steps.extract_excluded_products.outputs.excluded_products }}"
          excluded_products=$(echo "$excluded_products" | sed 's/\\/"/g')  # Remove backslashes
          echo "excluded_products: $excluded_products"
          denylistedFirstPathComponents="private let denylistedFirstPathComponents = Set([$excluded_products])"
          echo "denylistedFirstPathComponents: $denylistedFirstPathComponents"
          cat "GithubURLRouteRegistry.swift"
          sed -i "s/let denylistedFirstPathComponents = Set(\[.*\])/let denylistedFirstPathComponents = Set([$excluded_products])/" "GithubURLRouteRegistry.swift"
        working-directory: ${{ github.workspace }}
  
      - name: Commit and Push Changes
        run: |
          git config --global user.name "$(git config --get user.name)"
          git config --global user.email "$(git config --get user.email)"
          git add esraaapady/New-Repository/GitHubURLRouteRegistry.swift
          git commit -m "Update denylistedFirstPathComponents"
          git push
