name: Update deny list on iOS Client test
on:
  push:
    branches:
      - main
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout First Repository
        uses: actions/checkout@v2

      - name: Determine File Changes
        id: file_changes
        run: |
          echo "::set-output name=changes::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

      - name: Skip If No File Changes
        run: |
          if [ -z "${{ steps.file_changes.outputs.changes }}" ]; then
            echo "No changes detected in the apple-app-site-association file. Skipping update."
            exit 0
          fi

      - name: Read apple-app-site-association
        id: read_aasa
        run: |
          content=$(cat apple-app-site-association)
          echo "::set-output name=aasa_content::$content"

      - name: Extract excludedProducts
        id: extract_excluded_products
        run: |
          aasa_content=$(cat apple-app-site-association)
          echo "aasa_content: $aasa_content"
          excluded_products=$(echo "$aasa_content" | jq -r '.applinks.substitutionVariables.excludedProducts | join(", ")' | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')
          echo "excluded_products: $excluded_products"
          echo "::set-output name=excluded_products::$excluded_products"

      - name: Checkout Second Repository
        uses: actions/checkout@v2
        with:
          repository: esraaapady/New-Repository  # Replace with github/mobile-ios
          token: ${{ secrets.PAT_TOKEN }}

      - name: Print Current Working Directory
        run: |
          pwd
        working-directory: ${{ github.workspace }}

      - name: Update denylistedFirstPathComponents Method
        run: |
          excluded_products="${{ steps.extract_excluded_products.outputs.excluded_products }}"
          excluded_products=$(echo "$excluded_products" | sed 's/\\/"/g')  # Remove backslashes
          echo "excluded_products: $excluded_products"
          awk -v excluded_products="$excluded_products" '/private let denylistedFirstPathComponents = Set\(\[/ { print "private let denylistedFirstPathComponents = Set([" excluded_products "])"; next }1' GithubURLRouteRegistry.swift > temp.swift && mv temp.swift GithubURLRouteRegistry.swift
          # for testing, remove later
          cat "GithubURLRouteRegistry.swift"

          # Print the content of the modified file (remove later)
          echo "Modified File Content:"
          cat "GithubURLRouteRegistry.swift"

          # Configure git user for the repository
          git config --global user.name Hubot
          git config --global user.email hubot@users.noreply.github.com

          # Create a unique branch name
          branch_name="update/deny-file-$(date +'%s')"

          # Create a new branch and switch to it
          git switch -c $branch_name

          # Stage and commit the changes
          git add .
          git commit -m "Update deny file"

          # Push the branch to the remote repository
          git push origin $branch_name
